version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid

  selenium-node-chrome:
    image: selenium/node-chrome:latest
    container_name: selenium-node-chrome
    networks:
      - grid
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2g

  selenium-node-edge:
    image: selenium/node-edge:latest
    container_name: selenium-node-edge
    networks:
      - grid
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2g

  selenium-node-firefox:
    image: selenium/node-firefox:latest
    container_name: selenium-node-firefox
    networks:
      - grid
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2g

networks:
  grid:
    external: true
